# Generated by Django 3.1 on 2020-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liber',
            fields=[
                ('titulli', models.CharField(max_length=255)),
                ('autori', models.CharField(max_length=255)),
                ('cmimi', models.CharField(max_length=255)),
                ('img_src', models.CharField(max_length=255)),
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
