# Generated by Django 3.1 on 2020-09-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='_id',
            new_name='iid',
        ),
        migrations.AddField(
            model_name='autor',
            name='librat',
            field=models.ManyToManyField(to='app.Liber'),
        ),
    ]
