# Generated by Django 3.1 on 2020-09-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200908_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liber',
            old_name='_id',
            new_name='iid',
        ),
    ]
